# -*- coding: utf-8 -*-
"""Credit card.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wrIaTCsVJABSYvnGIi3OiMcOFFtPPjFE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

import plotly.express as px
import plotly.graph_objects as go

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/creditcard.csv")
print(df.head())

print("\nMissing Values:")
print(df.isnull().sum())

df = df.drop_duplicates()

print("\nDataset Shape After Removing Duplicates:", df.shape)

# Check data types
print("\nData Types:")
print(df.dtypes)

"""DESCRIPTIVE STATISTICS"""

print("\nStatistical Summary:")
print(df.describe())

# Average transaction amount
avg_amount = df["Amount"].mean()
print("\nAverage Transaction Amount:", avg_amount)

# Fraud vs Normal transaction count
fraud_count = df["Class"].value_counts()

print("\nFraud vs Normal Transactions:")
print(fraud_count)

"""FRAUD BEHAVIOR ANALYSIS"""

normal_transactions = df[df["Class"] == 0]
fraud_transactions = df[df["Class"] == 1]

print("\nNormal Transactions:")
print(normal_transactions.describe())

print("\nFraud Transactions:")
print(fraud_transactions.describe())

"""GROUP BASED ANALYSIS"""

# Average amount by class
group_analysis = df.groupby("Class")["Amount"].mean()

print("\nAverage Transaction Amount by Class:")
print(group_analysis)

"""RELATIONSHIP ANALYSIS"""

correlation = df.corr()

"""DATA VISUALIZATION"""

sns.set_style("whitegrid")

"""Fraud Distribution"""

plt.figure(figsize=(6,4))
sns.countplot(x='Class', data=df)
plt.title("Fraud vs Normal Transactions")
plt.xlabel("Class (0 = Normal, 1 = Fraud)")
plt.ylabel("Count")
plt.show()

"""Transaction Amount Distribution"""

plt.figure(figsize=(8,5))
sns.histplot(df['Amount'], bins=50, kde=True)
plt.title("Transaction Amount Distribution")
plt.xlabel("Amount")
plt.show()

"""Scatter Plot"""

plt.figure(figsize=(8,5))
sns.scatterplot(x='Time', y='Amount', hue='Class', data=df)
plt.title("Time vs Amount")
plt.show()

"""Box Plot"""

plt.figure(figsize=(6,4))
sns.boxplot(x='Class', y='Amount', data=df)
plt.title("Amount vs Fraud")
plt.show()

"""Correlation Heatmap"""

plt.figure(figsize=(14,10))
sns.heatmap(correlation, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

"""Risk Analysis"""

def risk_level(amount):
    if amount < 100:
        return "Low Risk"
    elif amount < 1000:
        return "Medium Risk"
    else:
        return "High Risk"

df["Risk_Level"] = df["Amount"].apply(risk_level)

print("\nRisk Level Distribution:")
print(df["Risk_Level"].value_counts())

"""LINEAR REGRESSION MODEL"""

# Independent Variables
X = df[['Time']]

# Dependent Variable
y = df['Amount']

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create Model
model = LinearRegression()

# Train Model
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

"""MODEL EVALUATION"""

r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("\nModel Evaluation")
print("R2 Score:", r2)
print("Mean Squared Error:", mse)

"""RESIDUAL ANALYSIS"""

residuals = y_test - y_pred

plt.figure(figsize=(8,5))
sns.histplot(residuals, bins=50, kde=True)
plt.title("Residual Distribution")
plt.xlabel("Residuals")
plt.show()

"""INTERACTIVE DASHBOARD"""

# Fraud Distribution Chart
fig1 = px.histogram(
    df,
    x="Class",
    title="Fraud vs Normal Transactions",
    labels={"Class": "Transaction Type"}
)

fig1.show()

# Transaction Amount Trend
fig2 = px.scatter(
    df,
    x="Time",
    y="Amount",
    color="Class",
    title="Transaction Amount Over Time"
)

fig2.show()

# Risk Level Chart
fig3 = px.pie(
    df,
    names="Risk_Level",
    title="Risk Level Distribution"
)

fig3.show()

# Correlation Heatmap
fig4 = go.Figure(
    data=go.Heatmap(
        z=correlation.values,
        x=correlation.columns,
        y=correlation.columns,
        colorscale='Viridis'
    )
)

fig4.update_layout(title="Correlation Heatmap")
fig4.show()

""" INSIGHTS & CONCLUSION"""

print("\nPROJECT INSIGHTS")
print("---------------------------")
print("1. Fraud transactions are very low compared to normal transactions.")
print("2. Transaction amount plays an important role in fraud detection.")
print("3. Some features show strong correlations with fraudulent activity.")
print("4. High-risk transactions can be identified using amount patterns.")
print("5. Dashboard visualizations help understand fraud behavior easily.")

print("\nThis Project Was Completed Successfully.")